name: Nightly Unit Test Execution

on:
  schedule:
    - cron: "0 2 * * *"  # Runs every night at 2 AM UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read  # Required for checking out private repositories

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js  # Modify this for your tech stack
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Change to match your project

      - name: Install Dependencies
        run: npm install  # Change to 'pip install -r requirements.txt' for Python

      - name: Run Unit Tests
        run: |
          npm test > test-results.txt  # Change to 'pytest --junitxml=test-results.xml' for Python

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Change for other providers
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Nightly Unit Test Report - ${{ github.repository }}"
          to: "recipient@example.com"
          from: "GitHub Actions <your-email@example.com>"
          body: |
            The nightly test run has completed.
            See attached test results.
          attachments: test-results.txt
